export const FETCH_BOARDS_START = 'FETCH_BOARDS_START';
export const FETCH_BOARDS_SUCCESS = 'FETCH_BOARDS_SUCCESS';
export const FETCH_BOARDS_ERROR = 'FETCH_BOARDS_ERROR';
export const ADD_BOARD = 'ADD_BOARD';
export const REMOVE_BOARD = 'REMOVE_BOARD';

export const FETCH_BOARD_START = 'FETCH_BOARD_START';
export const FETCH_BOARD_SUCCESS = 'FETCH_BOARD_SUCCESS';
export const FETCH_BOARD_ERROR = 'FETCH_BOARD_ERROR';
export const ADD_STICKER = 'ADD_STICKER';
export const REMOVE_STICKER = 'REMOVE_STICKER';
